-   repo: https://github.com/pre-commit/mirrors-black
    rev: v21.12b0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1
    hooks:
    -   id: flake8
